on:
  push:
    branches:
      - Appointment_Release

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: 📦 Publish project
      run: dotnet publish ./Appointment.csproj -c Release -o out/

    - name: 📴 App Offline
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: deploy/
        server-dir: /www/appointment/

    
    - name: ⚙️ Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: 🔄 Remove App Offline
      run: |
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} <<'EOF'
        rm /www/appointment/app_offline.htm
        bye
        EOF
