on:
  push:
    branches:
      - Appointment_Release

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout
      uses: actions/checkout@v4

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: 📦 Publish
      run: dotnet publish ./Appointment.csproj -c Release -o out/

    # 1) Take site offline
    - name: 📴 App Offline
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: deploy/
        server-dir: /appointment/

    # 2) Deploy published files
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: out/
        server-dir: /appointment/
        dangerous-clean-slate: true

    # 3) Bring site back online
    - name: 🔄 Remove App Offline
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} << 'EOF'
          rm /appointment/app_offline.htm
          bye
        EOF
